'use client'

import { motion } from 'framer-motion'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'

const fadeUp = {
  initial: { opacity: 0, y: 30 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true },
  transition: { duration: 0.5 },
}

const metrics = [
  {
    title: 'Current Output (kW)',
    description: 'Instantaneous power being generated by your panels right now. A 4kW system in Hyderabad typically peaks between 12pm–2pm at 3.5–4.2kW on clear days.',
    why: "Tells you if your system is performing at expected capacity at any given moment.",
  },
  {
    title: 'Daily Generation (kWh)',
    description: 'Total energy produced since 6am today. A 4kW system in Hyderabad generates 20–24 kWh on a good day given 5.5 peak sun hours.',
    why: "The primary metric for measuring your system's daily health.",
  },
  {
    title: 'Money Saved (₹)',
    description: 'Calculated at ₹6.30/unit — the TSSPDCL domestic tariff for Telangana. Every kWh your panels generate is a unit you didn\'t buy from the grid.',
    why: 'Direct financial impact. This is what determines your ROI timeline.',
  },
  {
    title: 'Grid Status',
    description: 'Three states: Selling (excess goes to grid), Buying (you draw from grid), Self-reliant (balanced).',
    why: 'A 4kW system in Hyderabad will typically be selling during peak hours and self-reliant in mornings and evenings.',
  },
  {
    title: 'Net Metering Earnings (₹)',
    description: 'When you sell excess units back to TSSPDCL you earn ₹3.14 per unit. This offsets your electricity bill directly.',
    why: 'Net metering is what makes residential solar financially viable in Telangana.',
  },
  {
    title: 'Monthly Projection vs Actual',
    description: "Projection multiplies today's output by 30. Actual tracks units generated so far this month.",
    why: 'Helps you anticipate your next electricity bill and plan around peak generation days.',
  },
]

const panelComparison = [
  {
    name: 'Polycrystalline',
    wattage: '330W',
    cost: '₹8,000/panel',
    efficiency: '16%',
    lifespan: '25 years',
    best: 'Budget installations with large roof space',
  },
  {
    name: 'Monocrystalline PERC',
    wattage: '400W',
    cost: '₹12,000/panel',
    efficiency: '20%',
    lifespan: '25 years',
    best: 'Standard residential installs — best value in India 2025',
  },
  {
    name: 'TOPCon',
    wattage: '450W',
    cost: '₹14,000/panel',
    efficiency: '23%',
    lifespan: '30 years',
    best: 'Space-constrained rooftops wanting maximum output',
  },
]

export default function HomeContent() {
  return (
    <div className="flex flex-col gap-12">

      <motion.section {...fadeUp} className="flex flex-col gap-4">
        <h2 className="text-2xl font-semibold">What we measure and why</h2>
        <p className="text-muted-foreground">
          Every value on this dashboard is derived from real formulas used in solar energy assessment.
        </p>
        <div className="flex flex-col gap-3">
          {metrics.map((metric, i) => (
            <motion.div
              key={metric.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.07 }}
            >
              <Card>
                <CardHeader className="pb-2">
                  <CardTitle className="text-base">{metric.title}</CardTitle>
                </CardHeader>
                <CardContent className="flex flex-col gap-2">
                  <p className="text-sm text-muted-foreground">{metric.description}</p>
                  <p className="text-sm">
                    <span className="font-medium">Why it matters: </span>
                    {metric.why}
                  </p>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>
      </motion.section>

      <motion.section {...fadeUp} className="flex flex-col gap-4">
        <h2 className="text-2xl font-semibold">Panel types compared</h2>
        <p className="text-muted-foreground">
          The ROI calculator compares three panel technologies available in India.
        </p>
        <div className="flex flex-col gap-3">
          {panelComparison.map((panel, i) => (
            <motion.div
              key={panel.name}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.1 }}
            >
              <Card>
                <CardContent className="pt-4 flex flex-col gap-2">
                  <div className="flex items-center justify-between">
                    <span className="font-semibold">{panel.name}</span>
                    <Badge variant="outline">{panel.efficiency} efficiency</Badge>
                  </div>
                  <div className="grid grid-cols-3 gap-2 text-sm text-muted-foreground">
                    <span>Wattage: {panel.wattage}</span>
                    <span>Cost: {panel.cost}</span>
                    <span>Lifespan: {panel.lifespan}</span>
                  </div>
                  <p className="text-sm">
                    <span className="font-medium">Best for: </span>
                    {panel.best}
                  </p>
                </CardContent>
              </Card>
            </motion.div>
          ))}
        </div>
      </motion.section>

      <motion.section {...fadeUp} className="flex flex-col gap-4">
        <h2 className="text-2xl font-semibold">How ROI is calculated</h2>
        <Card>
          <CardContent className="pt-4 flex flex-col gap-3 text-sm">
            <div className="flex flex-col gap-1">
              <span className="font-medium">Daily Generation (kWh)</span>
              <code className="bg-muted px-2 py-1 rounded text-xs">
                (Number of Panels × Wattage × Sun Hours) ÷ 1000
              </code>
            </div>
            <div className="flex flex-col gap-1">
              <span className="font-medium">Daily Savings (₹)</span>
              <code className="bg-muted px-2 py-1 rounded text-xs">
                Daily Generation × Electricity Rate (₹6.30)
              </code>
            </div>
            <div className="flex flex-col gap-1">
              <span className="font-medium">Breakeven (months)</span>
              <code className="bg-muted px-2 py-1 rounded text-xs">
                Total Investment ÷ Monthly Savings
              </code>
            </div>
            <div className="flex flex-col gap-1">
              <span className="font-medium">Net Position at month N</span>
              <code className="bg-muted px-2 py-1 rounded text-xs">
                (Monthly Savings × N) − Total Investment
              </code>
            </div>
          </CardContent>
        </Card>
      </motion.section>

      <motion.section {...fadeUp} className="flex flex-col gap-4">
        <h2 className="text-2xl font-semibold">Built with</h2>
        <div className="flex flex-wrap gap-2">
          {['Next.js 15', 'React 19', 'TypeScript', 'Tailwind CSS', 'ShadCN UI', 'Recharts', 'Framer Motion'].map((tech) => (
            <Badge key={tech} variant="secondary">{tech}</Badge>
          ))}
        </div>
      </motion.section>

    </div>
  )
}